site_name: Bonus FFB
site_url: https://kgmonteith.github.io/Bonus-FFB
repo_url: https://github.com/kgmonteith/Bonus-FFB
copyright: Copyright &copy; 2024 - 2025 Ken Monteith
theme:
  name: material
  palette: 
    scheme: default
    primary: indigo
    accent: indigo
#  icon:
#    logo: material/plane-car
  features:
    - navigation.tabs
    - toc.integrate
extra:
  analytics:
    provider: google
    property: G-24NFE8C173
nav:
  - Home: index.md
  - Download: https://github.com/kgmonteith/Bonus-FFB/releases
  - Getting started: getting-started.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
