site_name: Bonus FFB
site_url: https://kgmonteith.github.io/BonusFFB
repo_url: https://github.com/kgmonteith/BonusFFB
copyright: Copyright &copy; 2024 - 2025 Ken Monteith
theme:
  name: material
  palette: 
    scheme: default
    primary: indigo
    accent: indigo
  favicon: "data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🕹️</text></svg>"
  logo: "data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🕹️</text></svg>"
  features:
    - navigation.tabs
    - toc.integrate
extra:
  analytics:
    provider: google
    property: G-24NFE8C173
  social:
    - icon: fontawesome/brands/discord 
      link: https://discord.com/users/447499151337324574
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
  - Home: index.md
  - Download: https://github.com/kgmonteith/BonusFFB/releases
  - Getting started: getting-started.md